### ISSUE TITLE
check iCub's vision system and test in-hand-localization in Darmstadt

### ISSUE THREAD

**Issue by giuliavezzani** [tacman-fp7/handover#17]
- [x] test iCub **eyes**:
        - vertical and horizontal eyes alignment (eyes in position [ 0 0 0] should look straight ahead, procedure for fine tuning is available here http://wiki.icub.org/wiki/HeadFineCalibration)
- [x] iCub **arm** calibration: instructions [here](http://wiki.icub.org/wiki/ArmFineCalibration)

- [x] test:
         - **iKinGazeCtrl**
         - **yarpmotorgui**
- [x] calibrate **SFM** 
- [x] if not done, install:      
         - [stereo vision](https://github.com/robotology/stereo-vision )
         - [segmentation](https://github.com/robotology/segmentation)
         - [CGAL](https://github.com/CGAL/cgal)
- [x] parameter tuning of **dispBlobber**, starting from parameters found in [#12](https://github.com/tacman-fp7/handover/issues/12#issuecomment-262990625)
- [ ] test quality of point cloud acquisition and filtering, with parameter tuning of **`in-hand-localization` filters** (see [#12](https://github.com/tacman-fp7/handover/issues/12#issuecomment-262990625))
- [ ] test localization results
- [ ] test calibration between cameras and kinematics. If necessary, execute [depth2kin](https://github.com/robotology/icub-main/tree/master/src/tools)

**Comment by giuliavezzani** [comment]
- [ ] if not done, install:      
         - [stereo vision](https://github.com/robotology/stereo-vision )
         - [segmentation](https://github.com/robotology/segmentation)
         - [CGAL](http://www.cgal.org/download/linux.html)
- [ ] test:
         - **iKinGaze**
         - **yarpmotorgui**
- [ ] calibrate **SFM** 
- [ ] parameter tuning of **dispBlobber**, starting from parameters found in [#12](https://github.com/tacman-fp7/handover/issues/12#issuecomment-262990625)
- [ ] test quality of point cloud acquisition and filtering, with parameter tuning of **`in-hand-localization` filters** (see [#12](https://github.com/tacman-fp7/handover/issues/12#issuecomment-262990625))
- [ ] test localization results
- [ ] test calibration between cameras and kinematics. If necessary, install [depth2kin](https://github.com/robotology/icub-main/tree/master/src/tools) and execute it

**Comment by giuliavezzani** [comment]
@massimoregoli and @nawidj, I'd ask you to follow these steps to performe **fine calibration** of the `iCubDarmastadt01` head, since it may be required some mechanical tunings by @julijenv.

Hereafter, you find **step-by-step instructions** (that @julijenv already knows).

1. check in the `yarprobotinterface.ini` which is the used `.xml` (e.g. icub_all.xml);
2.  in that `.xml`, find the file concerning the head (e.g. head-cfw2_can0-mc.xml);
If the `iCubDarmstadt01` follows the standard of the robotology folder [**robots-configuration**](https://github.com/robotology/robots-configuration), the file of interest should be: 
[**hardware/mechanicals/head-cfw2_can0-mec.xml**](https://github.com/robotology/robots-configuration/blob/master/iCubDarmstadt01/hardware/mechanicals/head-cfw2_can0-mec.xml)
3. **NB**: you should not modify the standard file of their robot, but the **installed configuration file** in the **.local** folder. Thus, if they haven't install it, do:
       `yarp-config robot --import iCubDarmastad01`
and then, work in the **.local** repo
4. follow [these instructions](http://wiki.icub.org/wiki/HeadFineCalibration) to perform calibration.

If you need help for one of these step, please ask! :smiley: 
Likely, you will need julien's help for mechanical `eyes_tilt` calibration [head joint 3].

In the end, I'd ask you a picture of the iCub gaze :smiley:
@pattacini: is it ok this description?

Thanks guys!

**Comment by pattacini** [comment]
👍 @giuliavezzani 

cc @julijenv

**Comment by nawidj** [comment]
@giuliavezzani  we will perform the calibration when @julienv gets here. It looks like Alex has started installing the software you requested. We will be having a detailed look at the robot tomorrow.

**Comment by giuliavezzani** [comment]
thanks @nawidj !! :smiley:

**Comment by julienV** [comment]
not sure why i am getting referenced here, must be a typo ;)

**Comment by pattacini** [comment]
Ya, definitely, @julienV 😉 
@nawidj wanted to mention @julijenv instead.

**Comment by aparaschos** [comment]
@giuliavezzani 

We tested: Moving the right arm and tactile feedback from the right hand
The left arm has a broken tendon and therefore we removed it from the conf.

The eyes return images from the cameras

MotorGui, iKinGazeCtrl runs

Stereo vision, segmentation, CGAL installed 

depth2kin runs 

One note: the camera calibrator reads a config file from icub-main/app/cameraCalibration/conf/icubEyes.ini. Shouldn't instead read from robots-configurations/iCubDarmstadt01/icubEyes.ini?

**Comment by aparaschos** [comment]
@nawidj configs and code can be found in /home/icub/software_shared

**Comment by aparaschos** [comment]
One more note: please do not add files in .config or .local. Instead use the git repositories on branch tacman.

**Comment by giuliavezzani** [comment]
@paraschos thanks for your work!

Will the left arm be ok for next thursday?

Is there a file robots-configurations/iCubDarmstadt01/icubEyes.ini?
If yes, there should be some problems in the .ini files, because I think it should read from robots-configurations.

**Comment by nawidj** [comment]
@giuliavezzani don't worry the arm will be fixed.

**Comment by giuliavezzani** [comment]
Great! Thanks all! :smile:

**Comment by aparaschos** [comment]
@giuliavezzani Sure there is an iCubEyes.ini in the robots-conf repo. It would be great if you can compare the values and merge to two files. The reason that icub-main is being read is that we manually specify to read that one, no problem with the configuration files :)

**Comment by giuliavezzani** [comment]
@julijenv, did you check the `tilt` of the eyes? 
I'll be ready for working in Darmastadt on the 15th, in the morning. If you'll be still there, we can have a look together. 
Otherwise, if you notice something wrong, could you fix it ? That's the only DOF I can't calibrate by software :smiley:

**Comment by giuliavezzani** [comment]
- [x]  `meshlab` install on both the computers for point cloud visualization.

**Comment by massimoregoli** [comment]
@paraschos and @nawid, I had the following problems:

* I tried to launch `iKinGazeCtrl` and `iKinCartesianSolver` from **yarpmanager**, but I didn't manage to do it
* on the other hand, I managed to launch them from terminal
* If I launch them from terminal, other modules that require them are not able to find `iKinGazeCtrl` and `iKinCartesianSolver`, even if they are running.

Any hints or suggestions?

**Comment by giuliavezzani** [comment]
Summary after *day 1*:

- **iCub eyes** have been calibrated:

![20161215_144556](https://cloud.githubusercontent.com/assets/9597070/21238242/96ba3d46-c302-11e6-9c28-6b128d982ad8.jpg)

- handover code has been installed
- handover code is running
- `SFM` has been tested and calibrated [more or less]
- `dispBlobber` parameters have been updated with the good ones

**NB**:
- **performance** are very poor so far, need to be improved tomorrow.
- strange problems occurred with **cameras**: sometimes they can be started only after many trials (good .xml file is `Calib_Cameras.xml`)
- **arms** need absolutely to be calibrated

**Comment by giuliavezzani** [comment]
Basic functionalities of the vision system have been restored.

- Cameras outputs:

![cameras](https://cloud.githubusercontent.com/assets/9597070/21260179/0e79a8d0-c385-11e6-80c1-5ed575a57049.png)

- `SFM` and `dispblobber` outputs:

![sfm dispblob](https://cloud.githubusercontent.com/assets/9597070/21260214/35ecba4c-c385-11e6-982a-60895cb6e07c.png)

- blob selected by `in-hand-segmentation` module:

![dispblob](https://cloud.githubusercontent.com/assets/9597070/21260234/47f5ddae-c385-11e6-940a-0654671438f7.png)

**Comment by pattacini** [comment]
Great achievement 😄

**Comment by giuliavezzani** [comment]
Fine arm calibration executed.

This is the robot in the [**desired configuration**](http://wiki.icub.org/wiki/ArmFineCalibration), after `calibrationDelta` values have been updated in `left_arm-calib.xml` and `right_arm-calib.xml`:

![20161216_122230](https://cloud.githubusercontent.com/assets/9597070/21263298/3e9a7ea2-c396-11e6-850d-3b60718e4390.jpg)
![20161216_122249](https://cloud.githubusercontent.com/assets/9597070/21263300/40377f26-c396-11e6-9397-869c2c007d59.jpg)
![20161216_122350](https://cloud.githubusercontent.com/assets/9597070/21263302/41c8753e-c396-11e6-9a03-b4bed915012e.jpg)

**Comment by giuliavezzani** [comment]
## Summary of first tests on **`iCubDarmstadt01`**

###  Overview
[Here](https://github.com/tacman-fp7/handover/issues/17#issue-193362435) you can see the checklist of what I managed to do.
Just a few comments about the achieved goals:

- **arms and eyes calibration** has been performed, but they might be needed to be redone, considering the low performance and obtained results.

- the **installed code** (handover code and  `dispBlobber`) is correctly running

- it's quite difficult to correctly calibrate **`SFM`**, even if, finally, I managed to do it. For more details about this issue, see [#22](https://github.com/tacman-fp7/handover/issues/22)

### Results

Even if **`SFM`** was very unstable, I managed to get some point clouds.
- In particular, I could test **coarse filter** and **hand filter**. In the following figure, all the points are the output of the coarse filter, wherease the blu points are the output of the hand filter.
![point-clouds](https://cloud.githubusercontent.com/assets/9597070/21269882/c4aa83ca-c3b4-11e6-91e2-f919b868f044.png)

- unfortunately I didn't get good results for the **ellipse filter**, since it strongly relies on the fingers positions, that were, however, totally inaccurate. In this figure, the output of the cameras consists of the colorful points, whereas the 3 white points are the fingertips positions. They are not consistent...
![fingers-pos](https://cloud.githubusercontent.com/assets/9597070/21270126/8daa1f06-c3b5-11e6-8d53-0686f55d40ca.png)


Given the huge offset between kinematics and camera (even after the fine calibration of the arms), I tried to perform `**depth2kin**`. Sincerely, I don't know if depth2kin could be enough, or if the robot actually need a mechanical calibration..
However, I didn't manage to perform depth2kin due to the following reasons:

- **`SFM`** instability
- **torso oscillations** (see [#21](https://github.com/tacman-fp7/handover/issues/21))

All the points were discarded by the robot, the hand segmentation was unreliable and the robot swang too much, so that I decided to stop with the experiments.

**Comment by giuliavezzani** [comment]
### Tests will be performed when the `iCubDarmstadt01` will be at IIT.
